Chunya5/Controllers/BondsController.cs
using Chunya5.Data;
using Chunya5.Helper;
using Chunya5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Chunya5.Controllers
{
    public class BondsController : Controller
    {
        private readonly MyDbContext _context;

        public BondsController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Bonds
        public async Task<IActionResult> Index(string bondsCode,string bondsName,int page)
        {
            var pageSize = 8;
            var bonds = _context.Bonds.Where(x => x.IsDelete == false);
            if (!String.IsNullOrEmpty(bondsCode))
            {
                ViewBag.bondsCode = bondsCode;
                bonds = bonds
                    .Where(x => (x.BondsCode.Contains(bondsCode)));
            }
            if (!String.IsNullOrEmpty(bondsName))
            {
                ViewBag.bondsName = bondsName;
                bonds = bonds
                    .Where(x => (x.BondsName.Contains(bondsName)));
            }
            if (page == 0) page = 1;

            bonds.OrderBy(x => x.StartDate);

            return View(await PageList<Bonds>.CreatPageListAsync(bonds, page, pageSize));
        }



        public async Task<IActionResult> GetBondsByCode(string code)
        {
            //if (!String.IsNullOrWhiteSpace(code))
            //{
            //    return NotFound();
            //}

            var bonds = await _context.Bonds.FirstOrDefaultAsync(x=>x.BondsCode==code);
            if (bonds == null)
            {
                return NotFound();
            }
            return Ok(bonds);
        }

        // GET: Bonds/Create
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Bonds bonds)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bonds);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(bonds);
        }

        // GET: Bonds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bonds = await _context.Bonds.FindAsync(id);
            if (bonds == null)
            {
                return NotFound();
            }
            return View(bonds);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Bonds bonds)
        {
            if (id != bonds.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bonds);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BondsExists(bonds.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bonds);
        }

        // GET: Bonds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bonds = await _context.Bonds
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bonds == null)
            {
                return NotFound();
            }

            return View(bonds);
        }

        // POST: Bonds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bonds = await _context.Bonds.FindAsync(id);
            if (bonds != null)
            {
                bonds.IsDelete = true;
            }
            //_context.Bonds.Remove(bonds);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BondsExists(int id)
        {
            return _context.Bonds.Any(e => e.Id == id);
        }
    }
}

Chunya5/Controllers/PositionsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Chunya5.Data;
using Chunya5.Models;
using Chunya5.Helper;
using Chunya5.ViewModels;

namespace Chunya5.Controllers
{
    public class PositionsController : Controller
    {
        private readonly MyDbContext _context;

        public PositionsController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Positions
        public async Task<IActionResult> Index(string account, DateTime tradeDate, int page,bool isSearch)
        {
            var pageSize = 5;
            var positions = _context.Positions.Where(x => x.IsDelete == false) as IQueryable<Positions>;
            if (!String.IsNullOrEmpty(account))
            {
                ViewBag.account = account;
                positions = positions
                    .Where(x => (x.Account.Contains(account)));
            }
            if (tradeDate.Year != 1)
            { 
                ViewBag.date = tradeDate;
                positions = positions
                    .Where(x => x.TradeDate.Year == tradeDate.Year && x.TradeDate.Month == tradeDate.Month && x.TradeDate.Day == tradeDate.Day);
            }
            if (page == 0) page = 1;

            positions.OrderBy(x => x.TradeDate);
            
            return View(await PageList<Positions>.CreatPageListAsync(positions, page, pageSize));
        }
        


        // GET: Positions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Positions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,AddTime,UpdateTime,AddMan,ModifyMan,IsDeleteete,Accout,BondsCode,TradeDate,NetCost,InterestCost,AccInterest,AccUninterestImcome,RealizedInterestIncome,TotalInterestIncome,TradingProloss,FloatingPl,DenominattonHeld")] Positions position)
        {
            if (ModelState.IsValid)
            {
                _context.Add(position);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(position);
        }

        // GET: Positions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var position = await _context.Positions.FindAsync(id);
            if (position == null)
            {
                return NotFound();
            }
            return View(position);
        }

        // POST: Positions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,AddTime,UpdateTime,AddMan,ModifyMan,IsDeleteete,Accout,BondsCode,TradeDate,NetCost,InterestCost,AccInterest,AccUninterestImcome,RealizedInterestIncome,TotalInterestIncome,TradingProloss,FloatingPl,DenominattonHeld")] Positions position)
        {
            if (id != position.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(position);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PositionExists(position.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(position);
        }

        // GET: Positions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var position = await _context.Positions
                .FirstOrDefaultAsync(m => m.ID == id);
            if (position == null)
            {
                return NotFound();
            }

            return View(position);
        }

        // POST: Positions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var position = await _context.Positions.FindAsync(id);
            _context.Positions.Remove(position);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PositionExists(int id)
        {
            return _context.Positions.Any(e => e.ID == id);
        }
    }
}

Chunya5/Controllers/StatementController.cs
using Chunya5.Models;
using Microsoft.AspNetCore.Mvc;

namespace Chunya5.Controllers
{
    public class StatementController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ExportReport(string account,DateTime startTime,DateTime endTime)
        {
            ViewBag.Account = account;
            ViewBag.StartTime = startTime.ToLongDateString();
            ViewBag.EndTime = endTime.ToLongDateString();


            return View(new List<Statement>());
        }


    }
}

Chunya5/Controllers/TradesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Chunya5.Data;
using Chunya5.Models;
using Chunya5.Helper;

namespace Chunya5.Controllers
{
    public class TradesController : Controller
    {
        private readonly MyDbContext _context;

        public TradesController(MyDbContext context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }

        // GET: Trades
        public async Task<IActionResult> Index(string tradeAccount, DateTime tradeDate, int page)
        {
            var pageSize = 8;
            var trades = _context.Trade.Where(x=>x.IsDelete == false) as IQueryable<Trade>;

            if (!String.IsNullOrEmpty(tradeAccount))
            {
                trades = trades.Where(x=>x.Account.Contains(tradeAccount));
            }
            if(tradeDate.Year != 1)
            trades = trades.Where(x => x.TradeDate.Year == tradeDate.Year && x.TradeDate.Month == tradeDate.Month && x.TradeDate.Day == tradeDate.Day);
            

            if (page == 0) page = 1;

            trades.OrderBy(x => x.TradeDate);

            return View(await PageList<Trade>.CreatPageListAsync(trades, page, pageSize));
        }

        // GET: Trades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trade = await _context.Trade
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trade == null)
            {
                return NotFound();
            }

            return View(trade);
        }

        // GET: Trades/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Trade trade)
        {
            if (ModelState.IsValid)
            {
                var bonds = _context.Bonds.FirstOrDefault(x=>x.BondsCode == trade.BondsCode && x.IsDelete == false);
                if(bonds != null)
                {
                    _context.Add(trade);

                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trade);
        }

        // GET: Trades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trade = await _context.Trade.FindAsync(id);
            
            if (trade == null)
            {
                return NotFound();
            }
            return View(trade);
        }

        // POST: Trades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  Trade trade)
        {
            if (id != trade.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trade);
                    
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TradeExists(trade.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trade);
        }

        // GET: Trades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trade = await _context.Trade
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trade == null)
            {
                return NotFound();
            }

            return View(trade);
        }

        // POST: Trades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trade = await _context.Trade.FindAsync(id);
            
            _context.Trade.Remove(trade);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TradeExists(int id)
        {
            return _context.Trade.Any(e => e.Id == id);
        }

        

        
        
    }
}

Chunya5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap-4.6.1-dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Chunya5.styles.css" asp-append-version="true" />
    <style>
        h5 {
            margin-bottom: 0;
            background-image: linear-gradient(direction, red, white);
            font-weight: 600;
        }
    </style>
</head>
<body>
    <header style="background-color:#66bfff;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo.png" style="height:50px;" />
                    @*XQuent衡泰*@
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" style="display:flex;gap:30px; ">

                        <li class="nav-item active">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bonds" asp-action="Index">债券</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trades" asp-action="Index">交易</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Liquidation" asp-action="Index">日终清算</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statement" asp-action="Index">报表</a>
                            </li>*@
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
                                报表
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Positions" asp-action="Index">资产持仓</a>
                            </div>
                        </li>
                    </ul>
                    <span class="navbar-text" style="padding:0;">
                        <img src="~/img/logo5.jpg" style="height:60px" />
                    </span>
                </div>
            </div>
        </nav>
    </header>
    <div class="container " style="padding-bottom: 60px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted" style="margin-top:60px">
        <div class="container">
        &copy; 2022 - Chunya5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/jquery/jquery.slim.js"></script>*@
    <script src="~/lib/bootstrap-4.6.1-dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>